services:
  php:
    container_name: ${PROJECT_NAME}_php
    build: './website/SmartState-backend/php'
    networks:
      - SmartState-backend
    restart: unless-stopped
    volumes:
      - ./website/SmartState-frontend/:/var/www/html/
      - ./website/SmartState-frontend/css/:/var/www/html/${ROOT_URL}/css/
      - ./website/SmartState-frontend/img/:/var/www/html/${ROOT_URL}/img/
      - ./website/SmartState-frontend/js/:/var/www/html/${ROOT_URL}/js/

  apache:
    container_name: ${PROJECT_NAME}_apache
    build: './website/SmartState-backend/apache'
    depends_on:
      - php
      - postgres
    networks:
      - SmartState-frontend
      - SmartState-backend
    ports:
      - "${APACHE_PORT}:80"
    restart: unless-stopped
    volumes:
      - ./website/SmartState-frontend/:/var/www/html/
      - ./website/SmartState-frontend/css/:/var/www/html/${ROOT_URL}/css/
      - ./website/SmartState-frontend/img/:/var/www/html/${ROOT_URL}/img/
      - ./website/SmartState-frontend/js/:/var/www/html/${ROOT_URL}/js/

  postgres:
    container_name: ${PROJECT_NAME}_postgres
    build: 
      context: './website/SmartState-backend/postgres'
      args:
        ADMIN_EPPN: ${ADMIN_EPPN}
    environment:
      TZ: 'GMT'
      PGTZ: 'GMT'
    networks:
      - SmartState-backend
    env_file: ".env"
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes: 
      - ${PROJECT_NAME}-sql-data:/var/lib/postgresql/data

networks:
  SmartState-frontend:
  SmartState-backend:
volumes:
  SmartState-sql-data: